import { Inter } from "next/font/google";
import "./globals.css";
import Top from "./components/Top/Top";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white">
        <Top/>
        {children}</body>
    </html>
  );
}
